Ensure JAVA_HOME is set correctly

diff --git a/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server b/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
--- a/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
+++ b/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server
@@ -400,6 +400,7 @@ serverEnvDefaults()
     unset PID_FILE
   fi
 
+   # Determine location of java command.
   if [ -z "${JAVA_HOME}" ]
   then
     if [ -z "${JRE_HOME}" ]
@@ -547,31 +548,35 @@ serverEnvAndJVMOptions()
     mergeJVMOptions "${WLP_INSTALL_DIR}/etc/jvm.options"
   fi
 
-  # Determine location of Java Platform Module System (JPMS) modules directory
-  # Set JAVA_HOME if it is not already set.
+  # Try to find and set JAVA_HOME without invoking java, which is expensive.
+  # If all else fails, invoke java as a last resort.
   if [ -z "${JAVA_HOME}" ]; then
 
     # JAVA_HOME not set.  Locate java using the PATH.
     JAVA_PATH=$(command -v java)
     if [ -n "${JAVA_PATH}" ] ; then
-
+      
+      # Resolve symlinks.  JAVA_HOME is parent of parent of 'java'
       REAL_JAVA_PATH=$(findRealPath "${JAVA_PATH}")
-      JAVA_HOME=$(dirname "${REAL_JAVA_PATH}")/..
-      # The "exit" will cause JAVA_HOME to be unset in the unlikely case that JAVA_HOME is not a directory
-      JAVA_HOME="$(unset CDPATH; cd "${JAVA_HOME}" || exit; pwd)"
-      export JAVA_HOME
+      JAVA_HOME=$(dirname "$(dirname "${REAL_JAVA_PATH}")")
 
-      if [ -n "${REAL_JAVA_PATH}" ]; then
-         JPMS_MODULE_FILE_LOCATION=$(dirname "$(dirname "${REAL_JAVA_PATH}")")/lib/modules
-      fi
-    fi
-  else
-    JPMS_MODULE_FILE_LOCATION="${JAVA_HOME}/lib/modules"
+     # If this is NOT a true java home, determined by no 'lib' or no 'include',
+     # then, as a last resort, invoke java to extract java.home value    
+     if ! [ -d "$JAVA_HOME/lib" ] && ! [ -d "$JAVA_HOME/jre/lib" ] || ! [ -d "$JAVA_HOME/include" ]; then      
+      JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 | awk -F'=' '/java\.home/ {gsub(/^ +| +$/, "", $2); print $2}')
+     fi
+
+     export JAVA_HOME
+    fi  # if JAVA_HOME is not set and java is not in the PATH, then we cannot find Java.
   fi
 
-  # If we are running on Java 9 and up, apply Liberty's built-in java 9 options  
-  if [ -f "${JPMS_MODULE_FILE_LOCATION}" ]; then
-    mergeJVMOptions "${WLP_INSTALL_DIR}/lib/platform/java/java9.options"
+  if [ -n "${JAVA_HOME}" ]; then
+    JPMS_MODULE_FILE_LOCATION=${JAVA_HOME}/lib/modules
+
+    # If we are running on Java 9 and up, apply Liberty's built-in java 9 options  
+    if [ -f "${JPMS_MODULE_FILE_LOCATION}" ]; then
+       mergeJVMOptions "${WLP_INSTALL_DIR}/lib/platform/java/java9.options"
+    fi
   fi
 
   return $rc
